import { seedApiWorkspace } from "./decision-data";
import { expect, test, waitForServerEvents } from "./fixtures";

test("回答待ちバナーから個別回答し、再操作と別フォームの下書きを保つ", async ({ page, nod }) => {
  const api = await seedApiWorkspace(nod);
  const issue = await api.startedIssue("回答待ち", nod.codex);
  await api.ask(issue.id, "最初の質問", nod.codex);
  await api.ask(issue.id, "次の質問", nod.codex);
  await page.goto(`/issues/${issue.id}`);
  await waitForServerEvents(page);
  const banner = page.getByRole("region", { name: "回答待ち", exact: true });
  const panel = page.getByRole("region", { name: "未決事項", exact: true });
  const first = panel.getByRole("listitem").filter({ hasText: "最初の質問" });
  const second = panel.getByRole("listitem").filter({ hasText: "次の質問" });
  await expect(banner).toContainText("codex が回答を待っています");
  await expect(banner).toContainText("ほか 1 件");
  await second.getByRole("button", { name: "回答を記録" }).click();
  await second.getByRole("textbox", { name: "回答", exact: true }).fill("次の下書き");
  await banner.getByRole("button", { name: "回答する" }).click();
  await expect(first.getByRole("textbox")).toBeFocused();
  await first.getByRole("textbox").fill("最初の下書き");
  await first.getByRole("button", { name: "キャンセル" }).click();
  await banner.getByRole("button", { name: "回答する" }).click();
  await expect(first.getByRole("textbox")).toHaveValue("最初の下書き");
  await panel.getByRole("button", { name: "未決事項を追加" }).click();
  await panel.getByRole("textbox", { name: "未決事項", exact: true }).fill("追加の下書き");
  await banner.getByRole("button", { name: "回答する" }).click();
  await first.getByRole("button", { name: "記録する" }).click();
  await expect(banner).toContainText("次の質問");
  await expect(banner).not.toContainText("ほか 1 件");
  await banner.getByRole("button", { name: "回答する" }).click();
  await expect(second.getByRole("textbox")).toHaveValue("次の下書き");
  await second.getByRole("button", { name: "記録する" }).click();
  await expect(banner).toHaveCount(0);
  await panel.getByRole("button", { name: "未決事項を追加" }).click();
  await expect(panel.getByRole("textbox", { name: "未決事項", exact: true })).toHaveValue("追加の下書き");
});

test("原本の位置と色で長文とdetachedを表示し、外部回答で消える", async ({ page, nod }) => {
  const api = await seedApiWorkspace(nod);
  const issue = await nod.me.createIssue({ workspaceId: api.workspace.id, title: "長文確認", description: "バナーの前の説明" });
  const worktree = `${api.repo}/${"長い作業場所".repeat(30)}`;
  await nod.codex.startIssue(issue.id, { location: { branch: null, worktree } });
  const question = "複合インデックスを追加してよいですか？\n".repeat(15);
  await nod.codex.askQuestion(issue.id, question);
  await page.goto(`/issues/${issue.id}`);
  await waitForServerEvents(page);
  const banner = page.getByRole("region", { name: "回答待ち", exact: true });
  await expect(banner).toContainText("(detached)");
  await expect(banner).toContainText(worktree);
  await expect(banner).not.toContainText("Orca");
  await expect(banner).toHaveCSS("background-color", "rgb(253, 240, 216)");
  const description = await page.getByRole("region", { name: "説明", exact: true }).boundingBox();
  const bounds = await banner.boundingBox();
  const plan = await page.getByRole("region", { name: "計画", exact: true }).boundingBox();
  expect(bounds!.y).toBeGreaterThan(description!.y);
  expect(plan!.y).toBeGreaterThan(bounds!.y);
  await page.setViewportSize({ width: 1000, height: 900 });
  await expect(banner.getByRole("button", { name: "回答する" })).toBeVisible();
  expect(await banner.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
  await banner.getByRole("button", { name: "回答する" }).click();
  await expect(page.getByRole("textbox", { name: "回答", exact: true })).toBeFocused();
  await page.screenshot({ path: "../../.superpowers/sdd/2026-09-28-nod-detail-decisions-banner-plan/banner-browser.png", fullPage: true });
  const detail = await api.show(issue.id);
  await nod.me.answerQuestion(issue.id, "進めてください", { questionId: detail.questions[0]!.id });
  await expect(banner).toHaveCount(0);
  await expect(page.getByRole("textbox", { name: "回答", exact: true })).toHaveCount(0);
});

test.describe("回答失敗と送信中", () => {
  test.use({ allowedConsoleErrors: async ({}, use) => { await use([/status of 500/, /status of 409/]); } });
  test("失敗時の下書きと送信中の対象を保持する", async ({ page, nod }) => {
    const api = await seedApiWorkspace(nod);
    const issue = await api.startedIssue("再送", nod.codex);
    await api.ask(issue.id, "対象質問", nod.codex);
    await page.goto(`/issues/${issue.id}`);
    const banner = page.getByRole("region", { name: "回答待ち", exact: true });
    await banner.getByRole("button").click();
    const box = page.getByRole("textbox", { name: "回答", exact: true });
    await box.fill("回答の下書き");
    await page.route("**/api/issues/*/answer", (route) => route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: { code: "DB_BUSY", message: "保存失敗" } }) }));
    await page.getByRole("button", { name: "記録する", exact: true }).click();
    await expect(page.getByRole("alert")).toContainText("保存失敗");
    await expect(box).toHaveValue("回答の下書き");
    await page.unroute("**/api/issues/*/answer");
    let release = () => {};
    const gate = new Promise<void>((resolve) => { release = resolve; });
    await page.route("**/api/issues/*/answer", async (route) => { await gate; await route.continue(); });
    await page.getByRole("button", { name: "記録する", exact: true }).click();
    await expect(banner.getByRole("button")).toBeDisabled();
    await expect(page.getByRole("button", { name: "未決事項を追加", exact: true })).toBeDisabled();
    release();
    await expect(banner).toHaveCount(0);
    expect((await api.show(issue.id)).questions[0]!.answer).toBe("回答の下書き");
  });

  test("バナーの古い質問への回答は409を表示し別質問を回答しない", async ({ page, nod, request }) => {
    const api = await seedApiWorkspace(nod);
    const issue = await api.startedIssue("競合", nod.codex);
    await api.ask(issue.id, "競合する質問", nod.codex);
    await api.ask(issue.id, "残す質問", nod.codex);
    await page.goto(`/issues/${issue.id}`);
    await waitForServerEvents(page);
    const banner = page.getByRole("region", { name: "回答待ち", exact: true });
    const detail = await (await request.get(`/api/issues/${issue.id}`)).json();
    const response = await request.post(`/api/issues/${issue.id}/answer`, { data: { questionId: detail.questions[0]!.id, answer: "別画面の回答" } });
    expect(response.ok()).toBe(true);
    await banner.getByRole("button").click();
    await page.getByRole("textbox", { name: "回答", exact: true }).fill("競合する回答");
    await page.getByRole("button", { name: "記録する", exact: true }).click();
    await expect(page.getByRole("alert")).toContainText("記録できませんでした");
    await expect(banner).toContainText("残す質問");
    expect((await api.show(issue.id)).questions.find((q) => q.question === "残す質問")!.answer).toBeNull();
  });
});
