import {
  AlarmClock,
  Archive,
  ArchiveRestore,
  ArrowRight,
  Bell,
  BellOff,
  BellRing,
  Bot,
  Box,
  Calendar,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CirclePlay,
  CircleUser,
  CircleX,
  Columns3,
  Copy,
  ExternalLink,
  Eye,
  FileDiff,
  FilePlus,
  FileSearch,
  FileText,
  Gauge,
  GitMerge,
  GitPullRequest,
  GitPullRequestClosed,
  GitPullRequestDraft,
  Inbox,
  Info,
  Layers,
  List,
  ListChecks,
  ListFilter,
  LoaderCircle,
  type LucideIcon,
  MessageCircle,
  MessageCircleWarning,
  MessageSquare,
  Paperclip,
  Minus,
  OctagonAlert,
  Plus,
  RefreshCw,
  Reply,
  RotateCcw,
  Search,
  Settings,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SquarePen,
  Star,
  Tag,
  Terminal,
  Trash2,
  Undo2,
  X,
} from "lucide-react";

const ICONS = {
  "alarm-clock": AlarmClock,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-right": ArrowRight,
  bell: Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  bot: Bot,
  box: Box,
  calendar: Calendar,
  "chart-column": ChartColumn,
  check: Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-dot-dashed": CircleDotDashed,
  "circle-ellipsis": CircleEllipsis,
  "circle-play": CirclePlay,
  "circle-user": CircleUser,
  "circle-x": CircleX,
  "columns-3": Columns3,
  copy: Copy,
  "external-link": ExternalLink,
  eye: Eye,
  "file-diff": FileDiff,
  "file-plus": FilePlus,
  "file-search": FileSearch,
  "file-text": FileText,
  gauge: Gauge,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-pull-request-closed": GitPullRequestClosed,
  "git-pull-request-draft": GitPullRequestDraft,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  list: List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "loader-circle": LoaderCircle,
  "message-circle": MessageCircle,
  "message-circle-warning": MessageCircleWarning,
  "message-square": MessageSquare,
  paperclip: Paperclip,
  minus: Minus,
  "octagon-alert": OctagonAlert,
  plus: Plus,
  "refresh-cw": RefreshCw,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  search: Search,
  settings: Settings,
  "signal-high": SignalHigh,
  "signal-low": SignalLow,
  "signal-medium": SignalMedium,
  "square-pen": SquarePen,
  star: Star,
  tag: Tag,
  terminal: Terminal,
  "trash-2": Trash2,
  "undo-2": Undo2,
  x: X,
} satisfies Record<string, LucideIcon>;

// nod.pen のアイコン名（lucide の名前）で指定する。
export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 14, color }: { name: IconName; size?: number; color?: string }) {
  const Component = ICONS[name];
  return <Component size={size} color={color ?? "currentColor"} strokeWidth={1.75} aria-hidden="true" />;
}
