import {
  Activity,
  AlarmClock,
  Archive,
  ArchiveRestore,
  ArrowDownToLine,
  ArrowRight,
  ArrowRightToLine,
  Ban,
  Bell,
  BellOff,
  BellRing,
  Bot,
  Box,
  Calendar,
  CalendarRange,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CirclePlay,
  CircleUser,
  CircleX,
  Columns3,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileDiff,
  FilePlus,
  FileSearch,
  FileText,
  FileWarning,
  Flag,
  Gauge,
  ImageOff,
  GitMerge,
  GitPullRequest,
  GitPullRequestClosed,
  GitPullRequestDraft,
  Inbox,
  Info,
  Layers,
  Link,
  List,
  ListChecks,
  ListFilter,
  LoaderCircle,
  type LucideIcon,
  MessageCircle,
  MessageCircleWarning,
  MessageSquare,
  Paperclip,
  Pencil,
  Minus,
  OctagonAlert,
  Play,
  Plus,
  RefreshCw,
  Reply,
  RotateCcw,
  Search,
  Settings,
  SignalHigh,
  SignalLow,
  SignalMedium,
  Sparkles,
  SquarePen,
  Star,
  Tag,
  Send,
  Target,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  X,
  createLucideIcon,
} from "lucide-react";

// lucide 1.x はブランドのアイコンを外したため、nod.pen の github（lucide 0.x の形）をここで定義する
const Github = createLucideIcon("github", [
  ["path", { d: "M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4", key: "tonef" }],
  ["path", { d: "M9 18c-4.51 2-5-2-7-2", key: "9comsn" }],
]);

const ICONS = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-right": ArrowRight,
  "arrow-right-to-line": ArrowRightToLine,
  ban: Ban,
  bell: Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  bot: Bot,
  box: Box,
  calendar: Calendar,
  "calendar-range": CalendarRange,
  "chart-column": ChartColumn,
  check: Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-dot-dashed": CircleDotDashed,
  "circle-ellipsis": CircleEllipsis,
  "circle-play": CirclePlay,
  "circle-user": CircleUser,
  "circle-x": CircleX,
  "columns-3": Columns3,
  copy: Copy,
  "external-link": ExternalLink,
  link: Link,
  eye: Eye,
  "file-diff": FileDiff,
  "file-plus": FilePlus,
  "file-search": FileSearch,
  "file-text": FileText,
  "file-warning": FileWarning,
  download: Download,
  flag: Flag,
  gauge: Gauge,
  "image-off": ImageOff,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-pull-request-closed": GitPullRequestClosed,
  "git-pull-request-draft": GitPullRequestDraft,
  inbox: Inbox,
  github: Github,
  info: Info,
  layers: Layers,
  list: List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "loader-circle": LoaderCircle,
  "message-circle": MessageCircle,
  "message-circle-warning": MessageCircleWarning,
  "message-square": MessageSquare,
  paperclip: Paperclip,
  pencil: Pencil,
  minus: Minus,
  "octagon-alert": OctagonAlert,
  play: Play,
  plus: Plus,
  "refresh-cw": RefreshCw,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  search: Search,
  settings: Settings,
  "signal-high": SignalHigh,
  "signal-low": SignalLow,
  "signal-medium": SignalMedium,
  sparkles: Sparkles,
  "square-pen": SquarePen,
  star: Star,
  tag: Tag,
  send: Send,
  target: Target,
  terminal: Terminal,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "undo-2": Undo2,
  x: X,
} satisfies Record<string, LucideIcon>;

// nod.pen のアイコン名（lucide の名前）で指定する。
export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 14, color }: { name: IconName; size?: number; color?: string }) {
  const Component = ICONS[name];
  return <Component size={size} color={color ?? "currentColor"} strokeWidth={1.75} aria-hidden="true" />;
}
