// web は core の型を import type だけで使う（spec の決定）。
// A の時点の写しを、C を取り込んで core が揃った H で再エクスポートに置き換えた。
// web のほかのファイルは、これまでどおりこのファイルから型を import する。足りない型は、この一覧に名前を足す。
export type {
  AcceptTriageInput,
  TriageSuggestions,
  DuplicateSuggestion,
  LabelSuggestion,
  AssigneeSuggestion,
  SuggestionReason,
  ReviewReport,
  ReviewIssue,
  IssueDocumentRef,
  ActivityItem,
  CompletionStats,
  Summary,
  SummaryItem,
  SummaryKind,
  SummarySection,
  CompletionBucket,
  LlmStats,
  LlmWorkload,
  LlmBucket,
  WorkTime,
  AgentState,
  AskResult,
  Comment,
  WorkLogKind,
  DocKind,
  DocumentContent,
  DocumentDetail,
  DocumentIssueLink,
  DocumentProjectLink,
  DocumentRef,
  DocumentSummary,
  Inbox,
  InboxQuestion,
  Issue,
  IssueCounts,
  IssueDetail,
  IssueList,
  IssueQuery,
  Notification,
  SubscriptionState,
  Plan,
  PlanStep,
  PrCheck,
  PrCheckState,
  PrReviewDecision,
  PrState,
  PrStatus,
  PrStatusError,
  PrStatusView,
  PlanTask,
  Project,
  ProjectDetail,
  ProjectStatus,
  ProjectSummary,
  UpdateProjectInput,
  Question,
  RelationType,
  Relations,
  Status,
  StepStatus,
  UpdateIssueInput,
  View,
  ViewInput,
  Workspace,
  WorkspaceLabel,
  AutomationSettings,
  AutomationRuleResult,
  AutomationRun,
  AutomationTargets,
} from "@nod/core";

// Workspace の作業規約。未登録なら API は null を返す
export interface WorkspaceRules {
  workspaceKey: string;
  body: string;
  updatedAt: string;
  updatedBy: string;
}

