// web は core の型を import type だけで使う（spec の決定）。
// A の時点の写しを、C を取り込んで core が揃った H で再エクスポートに置き換えた。
// web のほかのファイルは、これまでどおりこのファイルから型を import する。足りない型は、この一覧に名前を足す。
export type {
  AcceptTriageInput,
  ReviewReport,
  ReviewIssue,
  IssueDocumentRef,
  ActivityItem,
  AgentState,
  AskResult,
  Comment,
  DocKind,
  DocumentContent,
  DocumentRef,
  Inbox,
  InboxQuestion,
  Issue,
  IssueCounts,
  IssueDetail,
  IssueList,
  IssueQuery,
  Plan,
  PlanStep,
  PlanTask,
  Project,
  ProjectDetail,
  ProjectStatus,
  ProjectSummary,
  UpdateProjectInput,
  Question,
  RelationType,
  Relations,
  Status,
  StepStatus,
  UpdateIssueInput,
  View,
  ViewInput,
  Workspace,
} from "@nod/core";
